### PR TITLE
Added OCRO mappings and romanian translations to attribute-definitions

### PR DESCRIPTION
**Pull request by andrixnet**
Should fix https://github.com/opencaching/okapi/issues/402

I've added OCRO mappings and romanian language translations. 

I must admit it is quite hard do attribute management this way and I've made many mistakes along the way. Corrected some of them, I hope none remained.

### CODE REVIEW

**Comment by andrixnet** [comment]
I have put this file into OKAPI on the website and get the following: 

```
Cache Types:

1: Unknown type
2: Traditional
3: Multicache
4: Virtual 
5: Webcam 
6: Event 
7: Quiz
8: Moving
9: Podcast cache
10: Own cache

Log Types:

1: Found it
2: Didn't find it
3: Comment
4: Moved
5: Needs maintenance
6: Service was made
7: Attended
8: Will attend
9: Archived
10: Ready to search
11: Temporarily unavailable
12: OC Team comment

Attributes:

6: ONLY LOGABLE ON OPENCACHING - >>>> MISSING A-CODE MAPPING <<<<
        de: Nur bei opencaching logbar
        en: Only logable on Opencaching
        nl: Alleen te loggen op Opencaching
        pl: Dostępna tylko na Opencaching
        ro: Disponibilă doar pe Opencaching
12: HUNTING GROUNDS - >>>> MISSING A-CODE MAPPING <<<<
        de: Achtung: Jagdgebied
        en: Hunting grounds
        nl: Let op: jachtgebied
        pl: 
        ro: Atenţie, teren de vânătoare!
13: THORN - >>>> MISSING A-CODE MAPPING <<<<
        de: Achtung: Dornen
        en: Thorn
        nl: Let op: doornen
        pl: 
        ro: Atenţie, spini!
14: TICKS - >>>> MISSING A-CODE MAPPING <<<<
        de: Achtung: Zecken
        en: Ticks
        nl: Let op: teken
        pl: 
        ro: Atenţie, căpuşe!
18: PARKING AREA NEARBY - >>>> MISSING A-CODE MAPPING <<<<
        de: Parkplatz in der Nähe
        en: Parking area nearby
        nl: Parkeerplaats vlakbij
        pl: 
        ro: Parcare în apropiere
25: LONG HIKE - >>>> MISSING A-CODE MAPPING <<<<
        de: Längere Wanderung
        en: Long hike
        nl: Lange wandeling
        pl: 
        ro: 5km sau mai mult de parcurs pe jos, dus-întors.
30: >>>> ENGLISH NAME UNSET! <<<< - >>>> MISSING A-CODE MAPPING <<<<
        nl: Interesante plek
38: THIS CACHE CAN BE FOUND AT ANY TIME OF DAY OR WEEK. - >>>> MISSING A-CODE MAPPING <<<<
        en: This cache can be found at any time of day or week.
        nl: Deze cache kan 24/7 gedaan worden.
        ro: Geocutia poate fi găsită la orice oră
39: THIS CACHE CAN ONLY BE DONE AT CERTAIN TIMES OF DAY OR WEEK  - >>>> MISSING A-CODE MAPPING <<<<
        en: This cache can only be done at certain times of day or week 
        nl: Deze cache is niet alle tijden te doen.
40: ONE-MINUTE CACHE - A68
        en: One-minute cache
        nl: Een snelle oppikker
        pl: Szybka skrzynka
        ro: Geocutie la minut
41: GO GEOCACHING WITH CHILDREN - A70
        en: Go geocaching with children
        nl: Kindvriendelijke cache
        pl: Można zabrać dzieci
        ro: Hai la căutat împreună cu copiii
43: GEOHOTEL - A5
        en: GeoHotel
        nl: GeoHotel
        pl: GeoHotel
        ro: GeoHotel - gazdă pentru obiecte călătoare
44: ACCESSIBLE FOR DISABLED - A18
        en: Accessible for disabled
        nl: Rolstoel toegankelijk
        pl: Dostępna dla niepełnosprawnych
        ro: Accesibila persoanelor cu handicap aflate în scaun cu rotile
45: STEALTH REQUIRED - >>>> MISSING A-CODE MAPPING <<<<
        en: Stealth required
        ro: Fii discret în timp ce cauţi
47: COMPASS - A49
        en: Compass
        nl: Kompas nodig
        pl: Potrzebny kompas
        ro: Ai nevoie de o busolă
48: TAKE SOMETHING TO WRITE - A50
        en: Take something to write
        nl: Neem iets mee om te schrijven
        pl: Weź coś do pisania
        ro: Ai nevoie de creion/pix/ceva de scris
49: FIXED BY MAGNET - A6
        en: Fixed by magnet
        nl: Bevestigd met magneet
        pl: Przyczepiona magnesem
        ro: Fixată cu magnet
50: INFORMATION IN  MP3 FILE - A7
        en: Information in  MP3 file
        nl: Informatie met MP3 bestand
        pl: Informacje zapisane w MP3
        ro: Informaţii suplimentare în fişier audio
51: OFFSET CACHE - A8
        en: Offset cache
        pl: Offset cache
        ro: Geocutie decalată faţă de coordonatele iniţiale
52: BEACON - GARMIN CHIRP - A9
        en: Beacon - Garmin chirp
        nl: Beacon - Garmin chirp
        pl: Beacon - Garmin chirp
        ro: Baliză radio - Garmin chirp
53: DEAD DROP USB CACHE - A10
        en: Dead Drop USB cache
        nl: Dead Drop USB cache
        pl: Dead Drop USB skrzynka
        ro: Dead Drop USB
54: BENCHMARK - GEODETICT POINT - A2
        en: Benchmark - geodetict point
        pl: Benchmark - punkt geodezyjny
        ro: Marcaj topografic
55: CARTRIDGE  - A3
        en: Cartridge 
        pl: Scenariusz WIGO
        ro: Cartuş digital Werigo
56: LETTERBOX - A4
        en: Letterbox
        nl: Letterbox
        pl: Letterbox
        ro: Letterbox
60: NATURE - A28
        en: Nature
        nl: Cache met veel natuur
        pl: Umiejscowiona na łonie natury, lasy, góry itp
        ro: Geocutie ascunsă în mijlocul naturii
61: MONUMENTAL PLACE - A29
        en: Monumental place
        nl: Benchmark - geodetisch punt
        pl: Miejsce historyczne
        ro: Monument istoric
80: PERIODICAL/PAID - A73
        en: Periodical/Paid
        pl: Dostępna w określonych godzinach lub płatna
        ro: Acces doar în anumite ore sau zile sau cu taxă
81: YOU WILL NEED A SHOVEL - A51
        en: You will need a shovel
        nl: Een schep nodig
        pl: Potrzebna łopatka
        ro: Ai nevoie de o lopată
82: TORCH NEEDED - A52
        en: Torch needed
        nl: Een zaklamp is nodig
        pl: Potrzebna latarka
        ro: Ai nevoie de o lanternă
83: TAKE SPECIAL EQUIPMENT - A56
        en: Take special equipment
        nl: Neem gereedschap mee
        pl: Wymagany dodatkowy sprzęt
        ro: Ai nevoie de unelte sau echipament special
84: ACCESS ONLY BY WALK - A20
        en: Access only by walk
        nl: De cache is alleen te voet te bereiken
        pl: Dostępna tylko pieszo
        ro: Accesibilă doar mergând pe jos
85: BIKE - A27
        en: Bike
        nl: Deze cache is ook met de fiets te doen.
        pl: Dostępna rowerem
        ro: Recomandat cu bicicleta
86: BOAT - A57
        en: Boat
        nl: Er is een boot nodig
        pl: Dostępna tylko łodzią
        ro: Ai nevoie de o barcă
90: DANGEROUS CACHE - A59
        en: Dangerous Cache
        nl: Deze cache kan gevaarlijk zijn
        pl: Skrzynka niebezpieczna
        ro: Atenţie, pericol!
91: RECOMMENDED AT NIGHT - A42
        en: Recommended at night
        nl: Bij voorkeur in het donker te doen
        pl: Zalecane szukanie nocą
        ro: Recomandată noaptea
120: DRINKING WATER AVAILABLE NEARBY - >>>> MISSING A-CODE MAPPING <<<<
        en: Drinking water available nearby
        ro: În apropiere există o sursă de apă potabilă
155: SOLVING THIS REQUIRES YOU VISIT THE PLACE - >>>> MISSING A-CODE MAPPING <<<<
        en: Solving this requires you visit the place
        ro: Rezolvarea se poate găsi numai vizitând locul

Attribute notices:

There are three priorities: (!), (-) and ( )
(the last one ( ) can be safely ignored)

(!) Attribute 6 is not mapped to any A-code.
(!) Attribute 12 is not mapped to any A-code.
(!) Attribute 13 is not mapped to any A-code.
(!) Attribute 14 is not mapped to any A-code.
(!) Attribute 18 is not mapped to any A-code.
(!) Attribute 25 is not mapped to any A-code.
(!) Attribute 30 is not mapped to any A-code.
(!) Attribute 38 is not mapped to any A-code.
(!) Attribute 39 is not mapped to any A-code.
(-) Attribute A68 is missing a name in the 'ro' language.
    Local name: Geocutie la minut
    OKAPI name: >> none <<
(-) Attribute A70 is missing a name in the 'ro' language.
    Local name: Hai la căutat împreună cu copiii
    OKAPI name: >> none <<
(-) Attribute A5 is missing a name in the 'ro' language.
    Local name: GeoHotel - gazdă pentru obiecte călătoare
    OKAPI name: >> none <<
( ) Attribute A5 has a different name in the 'pl' language
    Local name: GeoHotel
    OKAPI name: GeoHotel Cache
(-) Attribute A18 is missing a name in the 'ro' language.
    Local name: Accesibila persoanelor cu handicap aflate în scaun cu rotile
    OKAPI name: >> none <<
(!) Attribute 45 is not mapped to any A-code.
(-) Attribute A49 is missing a name in the 'ro' language.
    Local name: Ai nevoie de o busolă
    OKAPI name: >> none <<
(-) Attribute A50 is missing a name in the 'ro' language.
    Local name: Ai nevoie de creion/pix/ceva de scris
    OKAPI name: >> none <<
(-) Attribute A6 is missing a name in the 'ro' language.
    Local name: Fixată cu magnet
    OKAPI name: >> none <<
( ) Attribute A7 has a different name in the 'pl' language
    Local name: Informacje zapisane w MP3
    OKAPI name: Opis zawiera plik audio
(-) Attribute A7 is missing a name in the 'ro' language.
    Local name: Informaţii suplimentare în fişier audio
    OKAPI name: >> none <<
( ) Attribute A7 has a different name in the 'nl' language
    Local name: Informatie met MP3 bestand
    OKAPI name: Beschrijving bevat een audio bestand
(-) Attribute A8 is missing a name in the 'ro' language.
    Local name: Geocutie decalată faţă de coordonatele iniţiale
    OKAPI name: >> none <<
( ) Attribute A9 has a different name in the 'pl' language
    Local name: Beacon - Garmin chirp
    OKAPI name: Beacon - Garmin Chirp
(-) Attribute A9 is missing a name in the 'ro' language.
    Local name: Baliză radio - Garmin chirp
    OKAPI name: >> none <<
(-) Attribute A10 is missing a name in the 'ro' language.
    Local name: Dead Drop USB
    OKAPI name: >> none <<
(-) Attribute A2 is missing a name in the 'ro' language.
    Local name: Marcaj topografic
    OKAPI name: >> none <<
( ) Attribute A2 has a different name in the 'pl' language
    Local name: Benchmark - punkt geodezyjny
    OKAPI name: W pobliżu punktu geodezyjnego
(-) Attribute A3 is missing a name in the 'ro' language.
    Local name: Cartuş digital Werigo
    OKAPI name: >> none <<
( ) Attribute A3 has a different name in the 'pl' language
    Local name: Scenariusz WIGO
    OKAPI name: Wherigo Cache
(-) Attribute A4 is missing a name in the 'ro' language.
    Local name: Letterbox
    OKAPI name: >> none <<
( ) Attribute A4 has a different name in the 'nl' language
    Local name: Letterbox
    OKAPI name: Letterbox (een stempel nodig)
( ) Attribute A4 has a different name in the 'pl' language
    Local name: Letterbox
    OKAPI name: Skrzynka typu Letterbox
(-) Attribute A28 is missing a name in the 'ro' language.
    Local name: Geocutie ascunsă în mijlocul naturii
    OKAPI name: >> none <<
( ) Attribute A28 has a different name in the 'pl' language
    Local name: Umiejscowiona na łonie natury, lasy, góry itp
    OKAPI name: Umiejscowiona na łonie natury (lasy, góry, itp.)
( ) Attribute A29 has a different name in the 'nl' language
    Local name: Benchmark - geodetisch punt
    OKAPI name: Lost Place
(-) Attribute A29 is missing a name in the 'ro' language.
    Local name: Monument istoric
    OKAPI name: >> none <<
(-) Attribute A73 is missing a name in the 'ro' language.
    Local name: Acces doar în anumite ore sau zile sau cu taxă
    OKAPI name: >> none <<
(-) Attribute A51 is missing a name in the 'nl' language.
    Local name: Een schep nodig
    OKAPI name: >> none <<
(-) Attribute A51 is missing a name in the 'ro' language.
    Local name: Ai nevoie de o lopată
    OKAPI name: >> none <<
(-) Attribute A52 is missing a name in the 'ro' language.
    Local name: Ai nevoie de o lanternă
    OKAPI name: >> none <<
(-) Attribute A52 is missing a name in the 'nl' language.
    Local name: Een zaklamp is nodig
    OKAPI name: >> none <<
(-) Attribute A56 is missing a name in the 'ro' language.
    Local name: Ai nevoie de unelte sau echipament special
    OKAPI name: >> none <<
(-) Attribute A56 is missing a name in the 'nl' language.
    Local name: Neem gereedschap mee
    OKAPI name: >> none <<
(-) Attribute A20 is missing a name in the 'ro' language.
    Local name: Accesibilă doar mergând pe jos
    OKAPI name: >> none <<
(-) Attribute A20 is missing a name in the 'nl' language.
    Local name: De cache is alleen te voet te bereiken
    OKAPI name: >> none <<
(-) Attribute A27 is missing a name in the 'ro' language.
    Local name: Recomandat cu bicicleta
    OKAPI name: >> none <<
( ) Attribute A27 has a different name in the 'nl' language
    Local name: Deze cache is ook met de fiets te doen.
    OKAPI name: Fietsen toegestaan
( ) Attribute A57 has a different name in the 'pl' language
    Local name: Dostępna tylko łodzią
    OKAPI name: Wymaga sprzętu pływającego
(-) Attribute A57 is missing a name in the 'nl' language.
    Local name: Er is een boot nodig
    OKAPI name: >> none <<
(-) Attribute A57 is missing a name in the 'ro' language.
    Local name: Ai nevoie de o barcă
    OKAPI name: >> none <<
(-) Attribute A59 is missing a name in the 'ro' language.
    Local name: Atenţie, pericol!
    OKAPI name: >> none <<
(-) Attribute A59 is missing a name in the 'nl' language.
    Local name: Deze cache kan gevaarlijk zijn
    OKAPI name: >> none <<
(-) Attribute A42 is missing a name in the 'nl' language.
    Local name: Bij voorkeur in het donker te doen
    OKAPI name: >> none <<
(-) Attribute A42 is missing a name in the 'ro' language.
    Local name: Recomandată noaptea
    OKAPI name: >> none <<
(!) Attribute 120 is not mapped to any A-code.
(!) Attribute 155 is not mapped to any A-code.
```

**Comment by andrixnet** [comment]
I don't understand why it says 
`6: ONLY LOGABLE ON OPENCACHING - >>>> MISSING A-CODE MAPPING <<<<`
because there is
```
     <attr acode="A1" categories="de-listing">
        <opencaching schema="OCDE" id="6"/>
        <opencaching schema="OCNL" id="6"/>
        <opencaching schema="OCRO" id="6"/>
```

**Comment by andrixnet** [comment]
I've run the okapi update cron job, still, it seems that this definition file is not (entirely?) used.

**Comment by following5** [comment]
The attributes on the website are cached for 24 hours. So it can take up to 24 hours until changes are used. On developer systems, they are active immediately.

**Comment by andrixnet** [comment]
How does OKAPI know it runs on developer machine? Is it related to node_id=4?

**Comment by andrixnet** [comment]
@following5 a bit off-topic: please help in relation to http://forum.opencaching.de/index.php?topic=4497.msg57441#msg57441

**Comment by following5** [comment]
> How does OKAPI know it runs on developer machine? Is it related to node_id=4? 

On the devel machine the DEBUG flag is set (see okapi_settings.php).

>  please help in relation to http://forum.opencaching.de/index.php?topic=4497.msg57441#msg57441

Here is the contact address for opencaching.eu: http://whois.domaintools.com/opencaching.eu

**Comment by following5** [comment]
> Here is the contact address for opencaching.eu: http://whois.domaintools.com/opencaching.eu

Oops, it says "not disclosed". Maybe someone at Opencaching.PL can help you. Otherwise, webmaster@opencaching.eu or postmaster@opencaching.eu may work.

**Comment by wrygiel** [comment]
@kojoty and @deg-pl might be able to tell you something more about opencaching.eu

**Comment by kojoty** [comment]
I know only that it seems:
- opencaching.eu is own by us (oc.pl) now
- dns is control at the same panel as opencaching.pl
- served page is hosted at our server
so if anyone has any new idea how this domain let's discuss...

**Comment by deg-pl** [comment]
Now it is static HTML page.
I think we should migrate it to Wiki.
Wiki is system easy to edit by everyone who has rights - not like present static page.

**Comment by andrixnet** [comment]
which wiki ? OCPL wiki? OCDE wiki? opencaching.eu wiki?

**Comment by deg-pl** [comment]
For now, the OCPL Wiki on our new server (because this solution more flexible than static page). But if you have an idea for a better use (#607) - we are open.

**Pull request merged**
