### PR TITLE
OCPL log text InputFilter class OKAPI usage refactor

### PR DESCRIPTION
**Pull request by kojoty**
@following5 

This is small fix for inputFilter usage.
Please note I don't have OCDE dev setup to test if it works there - but I hope there shouldn't be any issue..

### CODE REVIEW

**Comment by kojoty** [comment]
(I updated this PR - the previous version was mismatched)

**Comment by following5** [comment]
No issues with OCDE, but my OCPL develsite says:

`Class 'Utils\Text\InputFilter' not found`

The file Utils\Text\InputFilter.php is present. Probably an autoloader cofiguration issue. Here is how you can test it:

- Change Line 31 of okapi/services/logs/submit/WebService.php to 
`'min_auth_level' => 3, 'DEBUG_AS_USERNAME' => 'kojoty'`
- http://local.opencaching.pl/okapi/services/logs/submit?consumer_key=YourConsumerKey&cache_code=OPxxxx&logtype=Comment&comment_format=html&comment=<b>+tag+not+closed

**Comment by kojoty** [comment]
thanks - right - I double checked and I got reproduction at my dev as well... long story - yeah the autoloader issue - I'll update this PR soon - I close for now.

**Comment by following5** [comment]
Btw, there is an open issue: #412. That input filter is poor, does not correct some HTML errors. HTMLPurifier should be used instead (Utils/Text/UseInputFilter). E.g. editlog.php already applies UserInputFilter.

**Pull request closed without merging**
