### PR TITLE
Proposal for #502 

### PR DESCRIPTION
**Pull request by teiling88**
Proposal for https://github.com/opencaching/okapi/issues/502

### CODE REVIEW

**Comment by following5** [comment]
I would prefer a lowercase "core" here, consistent with "lib", "services" and "views". Then it's all lowercase on the top level.

**Comment by teiling88** [comment]
done

**Comment by following5** [comment]
Please rebase and adjust the use statements in the two conflicting files.

Review and test is ok so far, but I will comply to the OCPL quiet period for this change and merge not before Monday.

**Comment by teiling88** [comment]
> Please rebase and adjust the use statements in the two conflicting files.

done

**Comment by following5** [comment]
Thanks. I guess it was by accident that you merged instead of rebased? Merging master into a feature branch confuses Git history.

**Comment by teiling88** [comment]
No wrygiel told me this: https://github.com/opencaching/okapi/pull/467#issuecomment-321319250

You want a rebase what i prefer to *confusing* :-)

**Comment by following5** [comment]
> No wrygiel told me this: #467 (comment)

:-O

**Comment by following5** [comment]
The "Core" is still uppercase in some namespace statements:
`git grep "namespace okapi\\Core"`

<pre>
okapi/core/Cache.php:namespace okapi\Core;
okapi/core/Db.php:namespace okapi\Core;
okapi/core/FileCache.php:namespace okapi\Core;
okapi/core/Okapi.php:namespace okapi\Core;
okapi/core/OkapiDataStore.php:namespace okapi\Core;
okapi/core/OkapiErrorHandler.php:namespace okapi\Core;
okapi/core/OkapiLock.php:namespace okapi\Core;
okapi/core/OkapiServiceRunner.php:namespace okapi\Core;
okapi/core/OkapiUrls.php:namespace okapi\Core;
</pre>

Also, there are two new merge conflicts after some debugging and bugfixing commits; and the use statements in the new file `okapi/views/devel/test/View.php` need adjustment. Sorry for that.

Rebase or merge, whatever you prefer. ;)

**Comment by following5** [comment]
... and the deployment script will need another update, because Okapi.php is moved.

**Comment by teiling88** [comment]
> okapi/views/devel/test/View.php

where can i find this file?

> Rebase or merge, whatever you prefer. ;)

rebased :-D

**Comment by following5** [comment]
> where can i find this file?

It is in master and should have appeared in this branch after rebase. Is your master up-to-date? Or do you have some local Git exclude for directories named "test"?

**Comment by teiling88** [comment]
Ah i looked there before the rebase :-) 

it is fixed

**Comment by teiling88** [comment]
@following5 - is a merge possible? I want to update okapi on oc.de

**Comment by following5** [comment]
If have no confirmation yet from wrygiel that the changed deployment script has been installed. But I may do a workaround ...

**Comment by following5** [comment]
Houston, we have a problem.

OKAPI caught the following exception while executing API method request.
This is an error in OUR code and should be fixed. Please contact the
developer of the module that threw this error. Thanks!

<pre>
ERROR MESSAGE
ErrorException:
Argument 1 passed to okapi\services\caches\shortcuts\search_and_retrieve\WebService::call() must be an instance of okapi\core\Request\OkapiRequest, instance of okapi\Request\OkapiHttpRequest given
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/services/caches/shortcuts/search_and_retrieve/WebService.php(23): okapi\OkapiErrorHandler::handle(4096, 'Argument 1 pass...', '/srv/ocpl/okapi...', 23, Array)
#1 [internal function]: okapi\services\caches\shortcuts\search_and_retrieve\WebService::call(Object(okapi\Request\OkapiHttpRequest))
#2 /srv/ocpl/okapi/OkapiServiceRunner.php(137): call_user_func(Array, Object(okapi\Request\OkapiHttpRequest))
#3 /srv/ocpl/okapi/views/method_call/View.php(19): okapi\OkapiServiceRunner::call('services/caches...', Object(okapi\Request\OkapiHttpRequest))
#4 [internal function]: okapi\views\method_call\View::call('services/caches...')
#5 /srv/ocpl/okapi/lib/OkapiScriptEntryPointController.php(52): call_user_func_array(Array, Array)
#6 /srv/ocpl/okapi/index.php(46): okapi\lib\OkapiScriptEntryPointController::dispatch_request('/okapi/services...')
#7 {main}

--- OKAPI method called ---
/okapi/services/caches/shortcuts/search_and_retrieve
?langpref=pl%7Cen
&oauth_consumer_key=p9QkYcFzV7bWZemtJ5FT
&oauth_nonce=2cbda629e8a1abf8b6695f4bd0969e11
&oauth_signature_method=HMAC-SHA1
&oauth_timestamp=1505135159
&oauth_token=BPVtj5Cvre9HhurgF87D
&oauth_version=1.0
&retr_method=services%2Fcaches%2Fgeocaches
&retr_params=%7B%22fields%22%3A%20%22code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cis_found%22%7D
&search_method=services%2Fcaches%2Fsearch%2Fbbox
&search_params=%7B%22bbox%22%3A%2254.079071%7C15.482435%7C54.113379%7C15.519515%22%2C%22exclude_my_own%22%3A%22true%22%2C%22found_status%22%3A%22notfound_only%22%2C%22ignored_status%22%3A%22notignored_only%22%7D
&wrap=true
&oauth_signature=qAw8Vzx3ugsLyQx4fdJKvt1FisU%3D

--- OKAPI version ---
1578 (e488974ec6be971ca575b2b80941d4abaf500378)

--- Request headers ---
Accept-Charset: utf-8,iso-8859-1;q=0.8,utf-16;q=0.8,*;q=0.7
Accept-Language: en-US,*;q=0.9
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1
Host: opencaching.pl
Connection: Keep-Alive
Accept-Encoding: gzip
Cookie: ocpldata=eyJ1c2VyaWQiOjAsInVzZXJuYW1lIjoiIiwicGVybWFuZW50IjowLCJsYXN0bG9naW4iOiIiLCJzZXNzaW9uaWQiOiIiLCJhZG1pbiI6MCwibGFuZyI6InBsIn0%3D; PHPSESSID=06emae0e0f0l8hibfmuknv3sm2
</pre>

**Comment by teiling88** [comment]
I can't reproduce this issue - is it possible that old files wasn't deleted correctly?

**Comment by following5** [comment]
> Is it possible that old files wasn't deleted correctly?

Yes. Will do a cleanup PR at OCPL.

**Comment by following5** [comment]
The files are now deleted at OCPL sites.

**Comment by deg-pl** [comment]
@following5 we have serious problem with (not) display caches on cachemap3.

```
[Tue Sep 12 02:05:05.213571 2017] [:error] [pid 15745] [client 37.248.166.21:18672] PHP Fatal error:  Class 'okapi\\OkapiErrorHandler' not found in /srv/ocpl/lib/mapper_okapi.php on line 20, referer: https://opencaching.pl/cachemap-full.php
[Tue Sep 12 02:05:06.984275 2017] [:error] [pid 15831] [client 37.248.166.21:18674] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'include_once(/srv/ocpl/lib/../okapi/OkapiErrorHandler.php): failed to open stream: Nie ma takiego pliku ani katalogu' in /srv/ocpl/lib/ClassPathDictionary.php:86\nStack trace:\n#0 /srv/ocpl/lib/ClassPathDictionary.php(86): okapi\\core\\OkapiErrorHandler::handle(2, 'include_once(/s...', '/srv/ocpl/lib/C...', 86, Array)\n#1 /srv/ocpl/lib/ClassPathDictionary.php(86): {closure}()\n#2 [internal function]: {closure}('okapi\\\\OkapiErro...')\n#3 /srv/ocpl/lib/xmlmap.php(333): spl_autoload_call('okapi\\\\OkapiErro...')\n#4 /srv/ocpl/lib/xmlmap.php(93): tmp_Xmlmap->htmlFormat(Array)\n#5 /srv/ocpl/lib/xmlmap.php(9): tmp_Xmlmap->__construct()\n#6 {main}\n  thrown in /srv/ocpl/lib/ClassPathDictionary.php on line 86, referer: https://opencaching.pl/cachemap-full.php
```

**Comment by teiling88** [comment]
This looks a little bit strange. The Class okapi/OkapiErrorHandler didn't exist any more. It has moved to okapi\core\OkapiErrorHandler . 

A possible solution is to black list okapi namespace from autoloading? 
Autoloading is managed in okapi/autoload.php for the okapi Namespace.

**Comment by kojoty** [comment]
I've fixed the issues in OCPL code. We use Okapi through the facade class but paths in OCPL code weren't updated till now.

**Comment by teiling88** [comment]
Ah i got the already fixed version :-)

**Comment by following5** [comment]
OKAPI must only be accessed through Facade. To disable and enable error handling, call `Facade::disable_error_handling()` and `Facade::reenable_error_handling()`.

**Pull request merged**
