### PR TITLE
Edit cache listings

### PR DESCRIPTION
**Pull request by following5**
This is work in progress for an update of `services/caches/edit`. As it is a BIG update, I put it here for the case there are comments / suggestions on the interface or implementation.

* Includes new options/fields for `services/caches/edit` , `services/caches/capabilities` and `services/attrs/attribute`.
* Todo: Add an option to `services/caches/geocache` to exclude the OCDE "listing is outdated" notice from the description - important for editing descriptions.
* Todo: Add edit options for country, region, additional waypoints and images.

### CODE REVIEW

**Comment by kojoty** [comment]
@following5 

I wonder if cache editing by OKAPI is a good idea for us. 

Generally this is great move, but how to be sure (in generally) that all operations are done when user edits cache by OKAPI or by webpage. 

This duplication of access ways is confusing for me. I think it would be good to think together how to do that... If we want to allow for edit we need to add more links between OKAPI and OCPL code...

Example of the problem:
- right now we have something like "altitude" for every cache.
- this is retrived from external service after every edit of cache coords (in OCPL code)
- how to deal with it in OKAPI? Does OKAPI code will update altitude as well or after OKAPI update altitude will be wrong?

**Comment by following5** [comment]
> Generally this is great move, but how to be sure (in generally) that all operations are done when user edits cache by OKAPI or by webpage

That's a general problem with OKAPI: We always need to make sure that it works the same as on the native OC site. Redundancy _may_ be avoided by consolidating logic into OKAPI and calling it via Facade. If OCPL developers are interested, I could help with that.

Regarding altitude: We could add that to the [NPA cronjob](https://github.com/opencaching/opencaching-pl/blob/master/util.sec/cron/modules/cache_npa_areas.class.php). When cache coordinates are changed, a DB trigger sets `caches.need_npa_recalc = 1`, and then this cronjob calculates the NPAs. Could also call the altutide calculation function.

As long as that does not work, we could restrict coordinate editing to OCDE.

**Comment by following5** [comment]
The rational for OKAPI cache editing is to allow easy on-site geocache maintenance for the owners. E.g. loggers complain about off-coordinates => owner goes to the cache, opens the cache in mobile app and clicks "correct coordinates". New coordinates are measured and automatically stored. Could do the same with additional waypoints. Could even record the stages of a new multicache on-site, directly adding them to the prepared listing.

**Comment by following5** [comment]
> it can be complete different that OCDE approach - what complicates OKAPI code much...

Actually, there are more differences in logging between OCDE/OCPL than in cache listings. Implementing the listing editor is simpler than logging.

> But if we starting to migrate more and more "logic" to the OKAPI 

That's not necessary at all for cache editing. Was just a general - and somewhat offtopic - suggestion to avoid redundancy. For the "altitude", my suggestion is to do it other way round an have the logic only in OCPL code. (Btw, for the "Merit Badge" issue #552, I would prefer the same.)

**Comment by following5** [comment]
I have editit my post above and striked-though the thing that you commented. It was offtopic.

**Comment by following5** [comment]
But I fully understand that you feel uncomfortable with creating more logic dependencies between OKAPI and OCPL. My goal was to make OKAPI complete -- I guess it's 80% complete now, and I would need 2-3 more months to make it 100%. But I can't do that without your support.

**Comment by kojoty** [comment]
@following5, I just share my minds...

like I told before I really appreciate your afford in OKAPI improvement.
If you need my support in any thing I will do what I can.  
I trust your perception in context of editing - let's go further with it.

**Comment by kojoty** [comment]
side thought: 

> owner goes to the cache, opens the cache in mobile app and clicks "correct coordinates".

I little afraid about accuracy of such measurements. I usually uses apps like gpsAverage to read coords by smartphone and it often gets results far from expectation... 
...but probably developers of the client apps should worry about it - not we :)

**Comment by following5** [comment]
Hmm okay, thanks.

Maybe it's better to do this in smaller steps than one big change.

**Comment by following5** [comment]
> Regarding altitude: We could add that to the NPA cronjob

Looks like the NPA cronjob is out of service at OCPL sites. Lots of `caches.need_npa_recalc` = 1 in the develsite database.

Will make a proposal for an OKAPI-sync cronjob, which can do all those things like update merit badges, altitudes, etc. 

Btw, it just took half a minute on my develsite to update a cache altitude. If it's done by cronjob, the user interface is not blocked.

**Comment by following5** [comment]
Added country and region editing and some supportive functions; now all fully reviewed and tested. This also allows easy implementation of searching by country, region and (description) language.

Description and region editing was more complicated than I expected ... but now works fine.

To do:
* https://github.com/opencaching/opencaching-pl/pull/1769
* editing of additional waypoints
* editing of images

**Comment by following5** [comment]
This is ready for release, but the description editing may be improved. Currently the method allows to save description, short description and hint in just one language per call. This keeps the OKAPI interface and implementation rather simple, but complicates error handling for clients.

Alternatively, JSON dictionaries with multiple language for each of the three fields could be accepted. Or just one two-level dictionary, with language first, and the field names and content on second level. This would make the OKAPI interface and implementation way more complicated, but the usage cleaner.

How to proceed?

**Comment by kojoty** [comment]
I understand cache edit by OKAPI is ready to go? 
@following5 do you need anything more to release it?

**Comment by following5** [comment]
A decision needs to be made on the interface (and implementation) for description editing, see above. As Wrygiel is no longer engaged in Okapi and I am busy with some OCPL tasks, this will have to wait.

**Comment by following5** [comment]
Also, this change exposes country and language name translations from OCPL database, which are partially broken (see https://github.com/opencaching/opencaching-pl/issues/1387#issuecomment-449685831). So it would be best to postpone it until either https://github.com/opencaching/opencaching-pl/issues/1387 or https://github.com/opencaching/okapi/issues/576 is done.

**Comment by following5** [comment]
>  JSON dictionaries with multiple language for each of the three fields could be accepted.

I think we should go for this option. It gives the cleanest interface:
* Input to caches/edit has identical format as output of caches/geocache(s)
* error handling is not compromised
* no nested dictionaries

**Comment by following5** [comment]
This change is blocked by several open issues:
* services/caches/capabilities must be rewritten
* OCPL capability settings must be recognized
* translations of OCPL country and language names should be improved
* description editing should be improved
* new OCPL cronjobs must be enabled at OC.RO (for altitude changes)

Also, attribute editing may be improved by adding an overwrite-by-new-set option, so developers don't need to calculate diffs for certain use cases.

**Comment by following5** [comment]
`countries` table is no longer used by OCPL code: https://github.com/kojoty/opencaching-pl/commit/44f3ef39ec5023f43f3915df9463bbbfc828ad82

**Pull request closed without merging**
