### PR TITLE
remove not necessary use statements

### PR DESCRIPTION
**Pull request by teiling88**
During my refactor work on opencaching.de i found some not necessary use statements. In this pr i only removed this ones.

### CODE REVIEW

**Comment by following5** [comment]
I think this change is generally ok, but would prefer that Wrygiel decides how to deal with it. I may do the testing if necessary.

**Comment by teiling88** [comment]
In PHPStorm - you get an notice for not used use statements - it quit easy to test ;-)

**Comment by following5** [comment]
I guess that PHPstorm also evaluates use statements in included files ...? For transparency and robustness, I would not rely on that but keep the duplicate `use`s in the main file. Include files may be restructured, and then something at another place can break without noticing it.

**Comment by following5** [comment]
>  keep the duplicate uses in the main file

... as far as the namespaces are referenced there

**Comment by wrygiel** [comment]
My current IDE doesn't notify me when `use`-es are missing, so removing them increases the chance of me accidentally committing a bug. I would switch to a better IDE, but I don't know one (and PHPStorm is not free). I think we should postpone merging this commit until all the developers have better IDEs.

**Comment by teiling88** [comment]
You can get free PHPStorm Licenses for your Project: https://www.jetbrains.com/buy/opensource/?product=phpstorm
opencaching.de already as get some licenses for free.
I removed only the not used use cases phpstorm mentioned.

**Comment by wrygiel** [comment]
Thanks. I had a look at the form. It seems there are some requirements we would need to satisfy first for OKAPI to be able to acquire it (e.g. a licence URL). But perhaps I will try one day :)

**Comment by wrygiel** [comment]
BTW, I think we could make use of Travis CI and some static code analyzer. I would very much like to experiment with GitHub's continuous integration options.

**Comment by teiling88** [comment]
This sounds good can i help you?

**Comment by wrygiel** [comment]
It was just a note to self :)

**Comment by teiling88** [comment]
scrutinizer makes good work if you want to look, visit our repo :-) https://github.com/OpencachingDeutschland/oc-server3

**Comment by wrygiel** [comment]
Looks promising. Thanks! I hope I will find the time to explore this option.

**Pull request closed without merging**
