### PR TITLE
misc - optimize okapi weekly usage report

### PR DESCRIPTION
**Pull request by teiling88**
For better readability a added the number_format function to the okapi weekly usage report.

### CODE REVIEW

**Comment by following5** [comment]
Four bugs in three lines of code. Okapi weekly reports use English locale, so decimal points are `.` and thousands separators `,`. Also, the "calls" columns should be expanded by two places, because we already have high 6-digit numbers at OC.pl which may excess the million.

**Comment by teiling88** [comment]
I fixed it.

**Comment by following5** [comment]
It's still buggy. Please test it yourself, then you will see what's wrong now.

**Comment by teiling88** [comment]
This view is before my change: 
image
So please tell me what kind of bug will add my pr to this view?

**Comment by teiling88** [comment]
So after month of silence I integrated this path in our production environment.

**Comment by teiling88** [comment]
Any update to this pr after nearly 3 weeks?

**Comment by teiling88** [comment]
Any updates to this pr? Or should we celebrate the anniversary on 4th of December?

**Comment by teiling88** [comment]
Any updates to this pr?

**Comment by teiling88** [comment]
Hey @following5, @wrygiel any updates to this pr?

**Comment by following5** [comment]
* Table header is misaligned
* Thousand's separators are missing in the summary number (total requests)
* Presentation is inconsistent - call numbers with thousands separators, runtimes without

**Pull request merged**
