### PR TITLE
OCPL log text InputFilter class OKAPI usage refactor

### PR DESCRIPTION
**Pull request by kojoty**
@following5 

what do you think about such solution?
If it is acceptable I need to deliver okapi_settings to OCPL code before merge of it.

BTW - I found and fixed small bug - _call should return array...

(as continuation of #553)

### CODE REVIEW

**Comment by following5** [comment]
Okay! Have added settings validation.

**Comment by following5** [comment]
Oops, there is an issue with `Settings::get()`. When called via Facade that early, this will follow:
* Settings::load_settings()
* OkapiErrorHandler::disable()
* restore_error_handler()

... without a preceding `set_error_handler()`. This will drop the OC errorhandler, if one was installed (OCDE does).

What about this:

```
$ocAutoloader = __DIR__ . '/../vendor/autoload.php';
if (file_exists($ocAutoloader))
    require_once $ocAutoloader ;
```

**Comment by following5** [comment]
Generally: Okapi error handling should be enabled before any Okapi functions are called (like Settings:get), but it should not be enabled before any Facade function is called. This is difficult to achieve if Settings:get is called from autoload.php.

**Comment by following5** [comment]
Generally,  it's a hen-and-egg problem between 1. initializing the autoloader, 2. inizializing Okapi errorhandling and 3. calling Settings::get(). No 2 should be done before no 3, but needs no 1, which does no. 3. :)

**Comment by following5** [comment]
Have merged the new log editing methods, which conflich with this commit. Log text processing has moved to LogsCommon.php. So this change must be re-applied.

**Comment by kojoty** [comment]
sure :) 
I have a busy days last days and this change has a low priority - I'll take care of it.

**Comment by kojoty** [comment]
OK, I updated this PR. To make it works at OCPL code we need to first add ClassPathDictionary.php to okapi_settings.php

**Comment by following5** [comment]
It still calls `Settings::get()` prior to `OkapiErrorHandler::init()`, which can cause trouble.

What about my suggestion to hard-code it in the same way as [this](https://github.com/opencaching/okapi/blob/master/okapi/Settings.php#L254)?
```
$ocAutoloader = __DIR__ . '/../vendor/autoload.php';
if (file_exists($ocAutoloader))
    require_once $ocAutoloader;
```

**Comment by following5** [comment]
I have tested your recent commit with this setting ...
```
'EXTERNAL_AUTOLOADER'=> __DIR__.'/vendor/autoload.php'
```
and also tested direct inclusion as proposed above. Still the same error: "Class 'Utils\Text\UserInputFilter' not found" :( Did I miss something?

**Comment by kojoty** [comment]
> I have tested your recent commit with this setting ...
> 
> ```
> 'EXTERNAL_AUTOLOADER'=> __DIR__.'/vendor/autoload.php'
> ```
> and also tested direct inclusion as proposed above. Still the same error: "Class 'Utils\Text\UserInputFilter' not found" :( Did I miss something?

Nope, for OCPL for now it should be: 
'EXTERNAL_AUTOLOADER'=> __DIR__.'/lib/ClassPathDictionary.php'

There are still a few "legacy" classes - after refactoring of this code OCPL will use composer autoloader, but for now this is necessary.

**Comment by following5** [comment]
Okay! Have added a commit which fixes the errorhandler initialization thing.

**Pull request merged**
